#!/usr/bin/env python

import argparse
import httplib2
import json
import os


def main():
    http = httplib2.Http()
    parser = argparse.ArgumentParser(description='Boot an OpenStack instance from RBD')
    parser.add_argument(
        '--endpoint',
        help='the Nova API endpoint (http://IP:port/vX.Y/)',
        default=os.getenv("NOVA_URL"),
        )
    parser.add_argument(
        '--image-id',
        help="The image ID Nova will pretend to boot from (ie, 1 -- not ami-0000001)",
        default=4,
        )
    parser.add_argument(
        '--volume-id',
        help='The RBD volume ID (ie, 1 -- not volume-0000001)',
        default=1,
        )
    parser.add_argument(
        '-v', '--verbose',
        action='store_true',
        default=False,
        help='be more verbose',
        )
    args = parser.parse_args()

    headers = {
        'Content-Type': 'application/json',
        'x-auth-project-id': 'admin',
        'x-auth-token': 'admin:admin',
        'Accept': 'application/json',
        }
    req = {
        'server':
            {
            'min_count': 1,
            'flavorRef': 1,
            'name': 'test1',
            'imageRef': args.image_id,
            'max_count': 1,
            'block_device_mapping': [{
                    'virtual': 'root',
                    'device_name': '/dev/vda',
                    'volume_id': args.volume_id,
                    'delete_on_termination': False,
                    }]
            }}

    resp, body = http.request(
        '{endpoint}/volumes/os-volumes_boot'.format(endpoint=args.endpoint),
        method='POST',
        headers=headers,
        body=json.dumps(req),
        )
    if resp.status == 200:
        print "Instance scheduled successfully."
        if args.verbose:
            print json.dumps(json.loads(body), indent=4, sort_keys=True)
    else:
        print "Failed to create an instance: response status", resp.status
        print json.dumps(json.loads(body), indent=4, sort_keys=True)

if __name__ == '__main__':
    main()
